### ISSUE TITLE
Performance improvement?

### ISSUE THREAD

**Issue by LasaleFamine** [AndriiHeonia/pixfinder#2]
Hi and firstly thank you so much for this awesome module.

I'm trying to use pixfinder, and specifically the `find()` method for finding a color specific bed cover and then replace it with a pattern using the `canvas`.

The problem is that sometimes the browser tab crashes during the search within ugly images (I'm working with max 300px of images' width). I have tried also on the server, using `node-canvas` and `jsdom` but although I managed to make it work, I'm often seeing my server instance hangs while searching for points.

So I'm wondering, is there any chance to improve the performance of pixfinder? Maybe also using AI (maybe also on the Cloud, like Google Vision or something else)? I really didn't find nothing so specific for my task besides it!

Thank you in advance for your response.

**Comment by AndriiHeonia** [comment]
Hello Alessio,
sorry for the delay with the response, I was on vacation.
If it's possible, could you please attach image and code sample on which it crashes in Chrome?

**Comment by LasaleFamine** [comment]
Hi @AndriiHeonia, thank you for your response, I hope you had a great vacation 😄

I made up an example on Glitch, but actually I can't reproduce the issue on my Mac with this prototype and currently I don't have a low-level smartphone for testing. Here is the example: https://glitch.com/edit/#!/pixfinder-test

You can check-out the results on the console trying the live version: https://pixfinder-test.glitch.me/

The complete implementation will use these coords found by pixfinder for calculating the area and then just "colorize" it on the canvas.

After all, do you think are there ways to improve this kind of task on low-level devices (or simply in general)?

**Comment by AndriiHeonia** [comment]
Hm., but Pixfinder calculates boundary of the found shape via [hull.js](https://github.com/AndriiHeonia/hull) library (and it's quite expensive). Do you really need only the boundary of the shape or you need all pixels of the shape? If you need all pixels then maybe it's enough for you to use [img-bfs](https://github.com/AndriiHeonia/img-bfs) library?

PS: I will think about possible optimizations of Pixfinder, but I can't guarantee results anytime soon.

**Comment by LasaleFamine** [comment]
Maybe I can use `img-bfs` with some colour checking like `pixfinder` does. Great hint, I really need to try, thank you so much. 

About optimizations, I thought (and tried) that switching some task into a Worker can be a nice way to improve the blocking work, but of course only not-DOM operation can be run inside the Worker, so I think it's not trivial with the `canvas` dependency.

I think at this point we can close this issue, I can go forward with `img-bfs`.

Thank you for the support, really appreciated 👍

**Comment by AndriiHeonia** [comment]
You are welcome.
